spring.application.name=GameVault

server.port=${PORT:8086}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/gamevault_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration